on:
  push

name: Test Jira Changelog

jobs:
  test-transition-issue:
    name: Jira Changelog
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: 'https://igooods.atlassian.net'
        JIRA_USER_EMAIL: 'd.tkachenko@dev.igooods.ru'
        JIRA_API_TOKEN: 'jr0GTmwljrHE1U47Far1A515'

    - name: Jira changelog
      id: changelog
      uses: uzicus/gajira-changelog@master
      with:
        from_branch: 'master'
        to_branch: 'develop'
        issue_format: '- <${issue.self}|${issue.key}> ${issue.fields["summary"]}'

    - run: echo ${{ steps.changelog.outputs.changelog }}